name: Deploy to VPS
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.USER_PASSWORD}}
          port: 22
          script: |
            cd ~/bm2
            git pull origin
            npm install
            npm run build
            pm2 delete all
            pm2 start "serve -s build -l 3000" --name bom-matcher
            
            
            
